### ISSUE TITLE
No such file or directory "config.cfg"

### ISSUE THREAD

**Issue by ghost** [reber0/Rpscan#1]
python3 Rpscan/rpscan.py -iL Sudomy/output/08-07-2020/targe.com/ip.txt -st masscan -r 3000 -c -a -s

No such file or directory "config.cfg"

**Comment by reber0** [comment]
cd Rpscan，then: python3 rpscan.py -iL Sudomy/output/08-07-2020/targe.com/ip.txt -st masscan -r 3000 -a -s -c config.cfg
